### ISSUE TITLE
Tree map left over items 

### ISSUE THREAD

**Issue by hanbyul-here** [RMI-Climate-Intelligence/oci#31]
(Moving some items @danielfdsilva wrote in the pr https://github.com/RMI-Climate-Intelligence/oci/pull/28) 

- [x] Improve animation between main and detail view

**Comment by hanbyul-here** [comment]
Pasting feedback from RMI related to treemap here. (Deleting redundant items from above)


- [ ] The blocks need to have consistent edge/fill color.  
- [ ] Replace "All (29)" with value for total emissions in grey box above tree map for toggle selected (see image below). 
- [ ] Subfilter for countries – probably need to change the style of filtering.   
- [ ] The treemap limited space parameters make it hard/impossible to read the full description of what some of the boxes mean. Add hover over each tree map box with print out of field name, country, emissions intensity, total production, total production (BOE volume) as a percentage of world production, total emission, total emissions as a percentage of world emission. 

Not treemap but total emission page
- [ ] Add methane only toggle to total emissions page. 
- [ ] Add OPEC/non-OPEC toggle to total emissions page. 
- [ ] For search bar: when user type in a country, the total emission page (treemap) for that country is shown.

**Comment by drewbo** [comment]
Going to close this in favor of the two remaining open items
