### ISSUE TITLE
Landing page items 

### ISSUE THREAD

**Issue by hanbyul-here** [RMI-Climate-Intelligence/oci#45]
1. Landing Page (https://app.mural.co/t/rmi6312/m/rmi6312/1634528466631/9496bf56a64176cbf4f32ccd9c4815fd1fef0ed0?sender=8ef99224-d579-400c-94cd-751177a5b587)
 
-  [x] 1.1 Add a logo “OCI+”
- [x] 1.2.Fix landing page redirect link of (OIL CLIMATE INDEX + GAS)
- [x] 1.3.Remove “Preview” 
- [x] 1.4.Change "Cases" to "Publications"* 
- [x] 1.5. Change text into "Search resources by field name or country".
- [x] 1.6. Add "Case Studies" tab here []
- [x] 1.7. Add "Emissions" (reads: ASSESSING GLOBAL OIL AND GAS EMISSIONS) 
- [x] 1.8.Edit descriptive text (to be done and sent by Shannon)
- [x] 1.9. Edit image - do we want an image that conveys issues more, like problematic behavior/flare stack/upset in the image
- [x] 1.10. Add NEW explainer "Videos" 
- [x] 1.11. Add box here for "Case Studies" Text below: "Run scenario analyses on oils and gases to see how different operational settings can affect emissions." 
- [x] 1.12. Change to horizontal logo 
- [x] 1.13. Add "Koomey Analytics"  and Move “Brown University” to the right 
- [x] 1.14. Add “Contributing Partners” section with four groups (to be determined) 

* We discussed that navigation might get too long if we put Publications back to Nav. I can’t remember how we concluded after.

**Comment by drewbo** [comment]
Notes:
- Need design updates on a few things
- Landing page redirect will work when deployed
